apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-demo-ffspostgres
spec:
  ports:
    - name: tcp-postgresql
      port: 5432
      protocol: TCP
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: opentelemetry-demo-postgresql
    app.kubernetes.io/name: postgresql
  type: ClusterIP
